-- CREATING A DATABASE
CREATE DATABASE IPMC_Management;
GO

USE IPMC_Management;
GO

-- ADMIN TABLE
CREATE TABLE Admin(
	AdminID		INT IDENTITY(1000,1) PRIMARY KEY NOT NULL,
	Username	NVARCHAR(MAX),
	Password	NVARCHAR(MAX)
);
GO
-- INSERTING A DEFAULT ADMIN
INSERT Admin
	VALUES('Ivy', 'Admin@1');
GO
SELECT * FROM Admin;

-- CREATING INSTRUCTOR'S TABLE
CREATE TABLE Instructor(
	InstructorsID	INT IDENTITY(1000,1) PRIMARY KEY NOT NULL,
	Firstname		NVARCHAR(100)		 NOT NULL,
	Lastname		NVARCHAR(100)        NOT NULL,
	Othername		NVARCHAR(100)		 NOT NULL,
	Department		NVARCHAR(100)		 NOT NULL,
	Gender			NVARCHAR(100)		 NOT NULL,
	Username		NVARCHAR(100)        NOT NULL,
	Password		NVARCHAR(MAX)	     NOT NULL,
	Telephone	    NVARCHAR(100)		 NOT NULL,
	Image			VARBINARY(MAX)		 NOT NULL
);
SELECT * FROM Instructor;
GO

-- CREATING STUDENT'S TABLE
CREATE TABLE Student(
	StudentsID	INT IDENTITY(1000,1) PRIMARY KEY NOT NULL,
	Firstname		NVARCHAR(100)		 NOT NULL,
	Lastname		NVARCHAR(100)        NOT NULL,
	Othername		NVARCHAR(100)		 NOT NULL,
	Department		NVARCHAR(100)		 NOT NULL,
	Gender			NVARCHAR(100)		 NOT NULL,
	Username		NVARCHAR(100)        NOT NULL,
	Password		NVARCHAR(MAX)	     NOT NULL,
	Telephone	    NVARCHAR(100)		 NOT NULL,
	Image			VARBINARY(MAX)		 NOT NULL
);
SELECT * FROM Student;
GO